site_name: Python Webpack Boilerplate
site_url: https://python-webpack-boilerplate.readthedocs.io/
repo_url: https://github.com/AccordBox/python-webpack-boilerplate
theme:
  name: "material"
  custom_dir: material/overrides
  palette:
    primary: teal
markdown_extensions:
  - codehilite
  - pymdownx.superfences:
  - markdown.extensions.admonition:
  - pymdownx.details
plugins:
  - search
nav:
  - Introduction: index.md
  - Setup With Django: setup_with_django.md
  - Setup With Flask: setup_with_flask.md
  - Frontend workflow: frontend.md
  - Code Linting: linting.md
  - Live Reload: live_reload.md
  - Tailwind CSS V4: setup_with_tailwind.md
  - Tailwind CSS V3: setup_with_tailwind3.md
  - Bootstrap: setup_with_bootstrap.md
  - React: react.md
  - Vue: vue.md
  - Use SWC: swc.md
  - Use ESBuild: esbuild.md
  - Typescript: typescript.md
  - Deployment Notes: deployment.md
  - Run NPM command at root directory: run_npm_command_at_root.md
  - Change Log: CHANGELOG.md
